# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBOutput

import tdw.flatbuffers

class ImageSensors(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsImageSensors(cls, buf, offset):
        n = tdw.flatbuffers.encode.Get(tdw.flatbuffers.packer.uoffset, buf, offset)
        x = ImageSensors()
        x.Init(buf, n + offset)
        return x

    # ImageSensors
    def Init(self, buf, pos):
        self._tab = tdw.flatbuffers.table.Table(buf, pos)

    # ImageSensors
    def AvatarId(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImageSensors
    def EnvId(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(tdw.flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ImageSensors
    def Sensors(self, j):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += tdw.flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .ImageSensor import ImageSensor
            obj = ImageSensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ImageSensors
    def SensorsLength(self):
        o = tdw.flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ImageSensorsStart(builder): builder.StartObject(3)
def ImageSensorsAddAvatarId(builder, avatarId): builder.PrependUOffsetTRelativeSlot(0, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(avatarId), 0)
def ImageSensorsAddEnvId(builder, envId): builder.PrependInt32Slot(1, envId, 0)
def ImageSensorsAddSensors(builder, sensors): builder.PrependUOffsetTRelativeSlot(2, tdw.flatbuffers.number_types.UOffsetTFlags.py_type(sensors), 0)
def ImageSensorsStartSensorsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ImageSensorsEnd(builder): return builder.EndObject()
